var termMap = {
    'arts': 'Arts and Culture',
    'culture': 'Arts and Culture',
    'astronomy': 'Astronomy',
    'auto': 'Auto and ATV',
    'atv': 'Auto and ATV',
    'biking': 'Biking',
    'boating': 'Boating',
    'camping': 'Camping',
    'canyoneering': 'Canyoneering',
    'caving':'Caving',
    'climbing': 'Climbing',
    'compass': 'Compass and GPS',
    'gps': 'Compass and GPS',
    'dog': 'Dog Sledding',
    'sledding': 'Dog Sledding',
    'fishing': 'Fishing',
    'flying': 'Flying',
    'food': 'Food',
    'golfing': 'Golfing',
    'guided': 'Guided Tours',
    'tours': 'Guided Tours',
    'hands-on': 'Hands-On',
    'hiking': 'Hiking',
    'horse': 'Horse Trekking',
    'hunting': 'Hunting and Gathering',
    'gathering': 'Hunting and Gathering',
    'skating': 'Ice Skating',
    'ranger': 'Junior Ranger Program',
    'history': 'Living History',
    'museum': 'Museum Exhibits',
    'paddling': 'Paddling',
    'film': 'Park Film',
    'playground': 'Playground',
    'scuba': 'Scuba Diving',
    'diving': 'Scuba Diving',
    'shopping': 'Shopping',
    'skiing': 'Skiing',
    'snorkeling': "Snorkeling",
    'snow': "Snow Play",
    'snowmobiling': 'Snowmobiling',
    'snowshoeing': 'Snowshoeing',
    'surfing': 'Surfing',
    'swimming': 'Swimming',
    'team': 'Team Sports',
    'sports': 'Team Sports',
    'tubing': 'Tubing',
    'water': 'Water Skiing',
    'wildlife': 'Wildlife Watching',
    
    'african': 'African American Heritage',
    'revolution': 'American Revolution',
    'seas': 'Ancient Seas',
    'animals': 'Animals',
    'archeology': 'Archeology',
    'architecture': 'Architecture and Building',
    'building': 'Architecture and Building',
    'arctic': 'Arctic',
    'asian': 'Asian American Heritage',
    'aviation': 'Aviation',
    'banking': 'Banking',
    'birthplace': 'Birthplace',
    'burial': 'Burial',
    'canyons': 'Canyons',
    'caves': 'Caves',
    'climate': 'Climate Change',
    'coasts': 'Coasts',
    'colonization': 'Colonization',
    'commerce': 'Commerce',
    'dams': 'Dams',
    'dunes': 'Dunes',
    'engineering': 'Engineering',
    'enslavement': 'Enslavement',
    'estuaries': 'Estuaries',
    'explorers': 'Explorers',
    'farming': 'Farming',
    'fire': 'Fire',
    'foothills': 'Foothills',
    'forests': 'Forests',
    'forts': 'Forts',
    'fossils': 'Fossils',
    'geology': 'Geology',
    'geothermal': 'Geothermal',
    'glaciers': 'Glaciers',
    'glasslands': 'Grasslands',
    'depression': 'Great Depression',
    'groundwater': 'Groundwater',
    'hispanic': 'Hispanic American Heritage',
    'immigration': 'Immigration',
    'craters': 'Impact Craters',
    'incarceration': 'Incarceration',
    'industry': 'Industry',
    'laborer': 'Laborer',
    'lakes': 'Lakes',
    'landscape': 'Landscape Design',
    'latino': 'Latino American Heritage',
    'LGBTQ': 'LGBTQ American Heritage',
    'maritime': 'Maritime',
    'medicine': 'Medicine',
    'migrations': 'Migrations',
    'military': 'Military',
    'monuments': 'Monuments',
    'mountains': 'Mountains',
    'music': 'Music',
    'native': 'Native American Heritage',
    'natural': 'Natural Sounds',
    'night': 'Night Sky',
    'sky': 'Night Sky',
    'oceans': 'Oceans',
    'pacific': 'Pacific Islander Heritage',
    'islander': 'Pacific Islander Heritage',
    'presidents': 'Presidents',
    'reconstruction': 'Reconstruction',
    'religion': 'Religion',
    'river': 'River',
    'rock': 'Rock',
    'scenic': 'Scenic Views',
    'schools': 'Schools',
    'science': 'Science',
    'social': 'Social Movements',
    'tropics': 'The Tropics',
    'thickets': 'Thickets and Shrublands',
    'shrublands': 'Thickets and Shrublands',
    'tragic': 'Tragic Events',
    'trails': 'Trails',
    'transportation': 'Transportation',
    'species': 'Unique Species',
    'urban': 'Urban America',
    'volcanoeos': 'Volcanoeos',
    'wars': 'Wars',
    'waterfalls': 'Waterfalls',
    'watersheds': 'Watersheds',
    'westward': 'Westward Expansion',
    'wetlands': 'Wetlands',
    'wilderness': 'Wilderness',
    "women's":"Women's History"
}

module.exports.termMap = termMap;
